config/routes.rb
Rails.application.routes.draw do
  get 'search', to: 'search#index'
  get 'users/profile'
  
  devise_for :users,  controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations' 
  }
  get '/u/:id', to: 'users#profile', as: 'user'

  # /posts/1/comments/4
  resources :posts  do
    resources  :comments
  end
  
  get 'about', to: 'pages#about'

  root "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence:true, length: {  minimum: 5, maximum:50}
  validates :body, presence:true, length: {  minimum: 10, maximum:1000}
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many_attached :images

  #Notification config into the Post and set up relationship 
  has_noticed_notifications model_name: 'Notification'
  has_many :notifications, through: :user, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[show index]
  before_action :set_post, only: %i[ show edit update destroy ]
  
  # GET /posts or /posts.json
  def index
    @posts = Post.all.order(created_at: :desc)  
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post.update(views: @post.views + 1)
    @comments = @post.comments.order(created_at: :desc)

    mark_notifications_as_read
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    
    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, images:[])
    end

    def mark_notifications_as_read
      if current_user
        notifications_to_mark_as_read = @post.notifications_as_post.where(recipient: current_user)
        notifications_to_mark_as_read.update_all(read_at: Time.zone.now)
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body, class:"form-control"%>
  </div>

  <div class="mb-3">
    <%= form.label :images %>
    <%= form.file_field :images, multiple: true, class:"form-control", id:"formFileMultiple"%>
  </div>

  
  <div>
    <%= form.submit class:"btn btn-secondary float-start" %>
  </div>
  <br/>
<% end %>

app/views/posts/_post.html.erb
  <br />
  
  <div class="card" id="<%= dom_id post %>">
    <div class="card-header">
      <%= post.title %>
    </div>
    
    <div id="carousel-<%= post.id %>" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-inner">
        <% post.images.each do |image| %>
          <% if image.representable? %>
            <% if image  ==  post.images.first  %>
              <div class="carousel-item active">
                <%= image_tag image, class:"d-block figure-img  mx-auto my-auto rounded",style: is_square ? "width:40rem; height: 28rem; ": "width:30rem; height: 21rem;" %>
              </div>
            <% else %>
              <div class="carousel-item">
                <%= image_tag image, class:"d-block figure-img img-fluid mx-auto my-auto rounded",style: is_square ? "width:40rem; height: 28rem; ": "width:30rem; height: 21rem;"  %>
              </div>
            <% end%>

          <% else %>%
            <%= link_to rails_blob_path(image, disposition: "attachment") do %> 
              <%= image_tag "placeholder.png", alt: "Download file" %> 
            <% end %> 
          <% end %>  
        <% end %>
        
        <button class="carousel-control-prev" type="button" data-bs-target="#carousel-<%= post.id %>" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button> 
        <button class="carousel-control-next" type="button" data-bs-target="#carousel-<%= post.id %>" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
      
    </div>

    <div class="card-body">
      <div class="d-flex figure">
        <%= image_tag post.user.avatar_icon, class:"figure-img rounded"%>
        <div class="align-self-center px-1">
          <h5><%= link_to post.user.name, user_path(post.user), class:"text-secondary"%></h5>
        </div>
        <h6 class="ms-auto">
          <%= pluralize(post.views, "view")%>
        </h6>
      </div>
      

      <p class="card-text"><%= post.body %></p>
    </div>
  
</div>

app/views/posts/edit.html.erb
<div class="container d-flex justify-content-center">
  <div class="card col-md-6 p-3 m-3">
    <h1>Editing post</h1>

    <%= render "form", post: @post %>
    <hr>
    <%= link_to "Show this post", @post, class:"btn btn-secondary my-2" %> 
    <%= link_to "Back to posts", posts_path, class:"btn btn-dark my-2" %>
  </div>
</div>

app/views/posts/index.html.erb
<div class = "container m-auto" id="posts">
  <div class="text-center">
    <h1>Posts</h1>
  </div>

  <div class="row p-2 mx-auto my-2">
    
    <%= link_to "Create new Post!", new_post_path, class:"btn btn-outline-success g-3" %>
    <% @posts.each do |post| %>
      <div class="col-12 col-md-6 col-lg-4">
        <%# modifique el partial "posts/post" %>
        <%= render partial: "posts/post", locals: {post: post, is_square: false} %>
        <%= link_to "Show this post", post, class:"btn btn-secondary" %>
      </div>
    <% end %>
  </div>

</div>    

app/views/posts/new.html.erb
<div class="container d-flex justify-content-center">
  <div class="card col-md-6 p-3 m-3">
  
    <h1>New post</h1>

    <%= render "form", post: @post %>

    <hr>
    
    <%= link_to "Back to posts", posts_path, class:"btn btn-dark" %>
    
  </div>
</div>

app/views/posts/show.html.erb
<div class="container mx-auto px-5">
  <%= render partial: "posts/post", locals: {post: @post, is_square: true}%>
  <% if current_user == @post.user%>
    <div class="btn-group float-end">
      <%= link_to "Edit this post", edit_post_path(@post), class:"btn btn-secondary" %> 
      
      <%= button_to "Destroy this post", @post, method: :delete, class:"btn btn-danger" %>
    </div>
    
  <% end %>
  
  <%= link_to "Back to posts", posts_path, class:"btn btn-dark"%>

  <br />
  <br />
  <%= render 'comments/form',
    post: @post,
    comment: @post.comments.build,
    submit_label: "Reply"%>
    <br/>
  <% @comments.each do |comment| %>
    <%= render 'comments/comment', 
      post: @post,
      comment: comment %>
    <br/>
  <% end %>
  
</div>

<%# # comment section %>